# ~/.config/starship.toml

# Colors:
# Orange -- #b77126
# Purple -- #8447bc 

# prompt format
format = """
[╭──](bold gray) $directory$git_branch$git_status
[╰─](bold gray)$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length=0
truncate_to_repo=false
style="bold #b77126"

[character]
success_symbol="[⧁](bold gray)"
error_symbol="[⮿](bold red)"

[git_branch]
format="[on](#8447bc) [$branch](bold #8447bc)"


[git_status]
format="$modified $staged"
modified="[*](#8447bc)"
staged='[\($count staged\)](#8447bc)'
