# ~/.config/starship.toml

# prompt format
format = """
[╭─](gray) $shell$directory[($git_branch$git_status)](bold yellow)$cmd_duration
[╰─](gray)$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 25 
command_timeout=1000
# Disable the blank line at the start of the prompt
add_newline = false

[shell]
disabled=false
powershell_indicator="[](blue)"
cmd_indicator="$powershell_indicator"
zsh_indicator="[](blue)"

[directory]
style="green"
truncate_to_repo=true

[git_status]
format="$stashed$staged$modified$untracked"
stashed=" [●](blue)"
staged=" [●](green)"
modified=" [●](yellow)"
untracked=" [●](red)"

[cmd_duration]
disabled=true
min_time="100"
format="[$duration]($style)"
style="dimmed white"

[git_branch]
format="[on $symbol$branch]($style)"
symbol=" "
style="white"

[character]
success_symbol="[❯](bold gray)"
error_symbol="[❯](bold red)"
